name: Build and Push Docker Image to AWS ECR
on:
  push:
    branches:
      - main
      - testing
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: check secret 1
        run: echo "${{ secrets.AWS_ACCESS_SECRET_KEY }}"
      - name: check secret 2
        run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
      - name: check secret 3
        run: echo "${{ secrets.REPO_NAME }}"
